export interface IDictItem {
    label: string
    description: string
}


export const dictionary: IDictItem[] = [
    { label: "ABT", description: "About — около, приблизительно" },
    { label: "AGN", description: "Again — опять, снова" },
    { label: "AS", description: "Подождите. AS 5 — подождите 5 минут" },
    { label: "AR", description: "Код обозначающий конец передачи" },
    { label: "BK", description: "Break (Прерывание) обычно применяется при работе полудуплексом, но чаще можно услышать как отметку конца передачи какого либо текста или информации, либо просьбу «вклиниться» в QSO двух радиолюбителей." },
    { label: "BTU", description: "Back to you означает конец передачи своей информации и готовность слушать передачу корреспондента" },
    { label: "BLG", description: "(БЛГ) от русского «благодарю» используется русскоязычными радиолюбителями, зарубежные радиолюбители иногда применяют при связи с русскоязычными радиолюбителями" },
    { label: "CUAGN", description: "See you again — увидимся снова" },
    { label: "CUL", description: "See you later — увидимся позже" },
    { label: "CQ", description: "Общий вызов — «Всем, всем»" },
    { label: "CONDX", description: "Conditions — условия чего-либо (чаще прохождения радиоволн)" },
    { label: "CW", description: "Continious wave, Code work — незатухающие колебания, работа кодом (азбукой Морзе) Общепринятое обозначение радиотелеграфа." },
    { label: "DE", description: "Предлог, обозначающий «от», «я». Например UA0LDK DE RV6ASX, можно «расшифровать» как «Радиостанция с позывным UA0LDK, я радиостанция с позывным RV6ASX» Или «DE RV6ASX» — » я RV6ASX»" },
    { label: "DX", description: "Дальняя, редкая станция, связь" },
    { label: "DR", description: "Dear — дорогой" },
    { label: "DSW", description: "ДСВ — сокращение от русского «До свидания»" },
    { label: "ES", description: "Союз «и»" },
    { label: "EX", description: "Бывший (в смысле вышедший из употребления) Например бывший позывной — EX CALL" },
    { label: "FB", description: "Fine business — превосходно, прекрасно, замечательно" },
    { label: "FER", description: "«За» Например, — «спасибо за связь» TNX FER QSO" },
    { label: "FREQ", description: "Frequency — частота" },
    { label: "GA", description: "Good Afternoon — добрый день" },
    { label: "GB", description: "До свидания" },
    { label: "GD", description: "Добрый день" },
    { label: "GE", description: "Добрый вечер" },
    { label: "GN", description: "Доброй ночи" },
    { label: "GL", description: "Good Luck — Удачи" },
    { label: "GLD", description: "Glad — рад" },
    { label: "GUHOR", description: "Вас не слышу. Еще можно услышать «полный GUHOR на частоте (диапазоне)»" },
    { label: "HAM", description: "Радиолюбитель имеющий передатчик. По поводу происхождения этого кода ходит много версий и легенд, какая из них верная точно никто не знает. Часто можно услышать или прочитать «аппаратура для Ham-radio» это означает «аппаратура для радиолюбителей увлекающихся радиоствязью»" },
    { label: "HPE", description: "Hope — надеюсь" },
    { label: "HR", description: "Here — здесь" },
    { label: "HRD", description: "Heard — слышал, слышу" },
    { label: "HI", description: "Выражение смеха" },
    { label: "HW", description: "? How? — Как? В смысле как дела? как меня слышите? как приняли?" },
    { label: "K", description: "от Key — ключ. Употребляется как знак окончания передачи и предложения перейти на передачу корреспонденту." },
    { label: "LID", description: "плохой, неопытный оператор" },
    { label: "LTR", description: "Letter — письмо" },
    { label: "MNI", description: "Many — много" },
    { label: "MTR", description: "Meter — метр, измеритель чего-либо" },
    { label: "NIL", description: "Ничего" },
    { label: "NR", description: "Number — номер. Второе значение Near — около." },
    { label: "NW", description: "Now — сейчас" },
    { label: "OK", description: "OK — из разговорного английского и русского языка — «Все хорошо» «Все правильно»" },
    { label: "OM", description: "Old man — приятель, старина (в смысле «привет, старина!»)" },
    { label: "OP", description: "Operator — оператор" },
    { label: "PA", description: "Power Amplifier — усилитель мощности" },
    { label: "PSE", description: "Please — Пожалуйста" },
    { label: "PSK", description: "Pfase Shift Keyng — вид цифровой связи, по русски можно перевести как фазовое ключевание" },
    { label: "PWR", description: "Power — Мощность" },
    { label: "R", description: "Right — Правильно, принял правильно" },
    { label: "RPT", description: "Repeat — Повторение. Report — Рапорт" },
    { label: "RIG", description: "Передатчик, аппаратура приемо-передачи" },
    { label: "RTTY", description: "Radioteletype — Радиотелетайп" },
    { label: "SIGS", description: " SIG Signals — Сигналы, сигнал" },
    { label: "SN", description: "Soon — Скоро" },
    { label: "SK", description: "Полный конец связи" },
    { label: "SPB", description: "СПБ — Спасибо" },
    { label: "SRI", description: "Sorry — Извините" },
    { label: "SSB", description: "Single Side Band — Однополосная модуляция" },
    { label: "STN", description: "Station — Станция" },
    { label: "SWL", description: "Short Wave Listener — Коротковолновик — наблюдатель" },
    { label: "TKS", description: "или TNX Thanks — Спасибо" },
    { label: "TU", description: "Thank you — благодарю вас" },
    { label: "TVI", description: "Television Interference — Помехи телевидению" },
    { label: "U", description: "You — Вы" },
    { label: "UR", description: "Your — Ваш" },
    { label: "VY", description: "Very — Очень" },
    { label: "YL", description: "Young Lady — Девушка" },
    { label: "XYL", description: "EX Young Lady — Женщина, Жена" },
    { label: "WX", description: "Погода" },
    { label: "ZDR", description: "ЗДР — Здравствуйте" },
    { label: "73", description: "Наилучшие пожелания" },
    { label: "88", description: "Любовь и поцелуй (шутка, передается оператору женщине)" },
    { label: "99", description: "Не хочу с вами работать. Аналогично русской фразе «идите на…» одно из редких грубых выражений в радиолюбительском эфире." },
];
